# Generated by Django 6.0.2 on 2026-10-07 09:25

from django.db import migrations, models


def rename_local_host_key(apps, schema_editor):
    # The built-in local host key was renamed devforge_local -> boldron_local.
    # Point existing published versions at the new key so they keep resolving.
    PublishVersion = apps.get_model('publishing', 'PublishVersion')
    PublishVersion.objects.filter(host='devforge_local').update(host='boldron_local')


def reverse_local_host_key(apps, schema_editor):
    PublishVersion = apps.get_model('publishing', 'PublishVersion')
    PublishVersion.objects.filter(host='boldron_local').update(host='devforge_local')


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0018_productvariant_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishversion',
            name='host',
            field=models.CharField(default='boldron_local', max_length=32),
        ),
        migrations.RunPython(rename_local_host_key, reverse_local_host_key),
    ]
