# Generated by Django 6.0.2 on 2026-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_releaserejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingconfiguration',
            name='mode',
            field=models.CharField(choices=[('managed', 'Platform-managed'), ('customer', 'Customer-managed')], default='managed', max_length=16),
        ),
    ]
