# Generated by Django 6.0.2 on 2026-10-08 06:49

from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    # Accounts that predate email verification are treated as already verified —
    # the feature only gates new self-serve sign-ups.
    User = apps.get_model("accounts", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
    ]
